### ISSUE TITLE
File posistion in Windows

### ISSUE THREAD

**Issue by agoralive** [MikeAleksa/solidity-docker-node#1]
Hi

What is the file position in Windows?

Where can I see the files I have created?

**Comment by MikeAleksa** [comment]
If you want to persist data from the docker container to the file system you will need to use a volume when you start the container: https://docs.docker.com/storage/volumes/

I recommend using the docker container as a VSCode devcontainer if you're using VSCode.

Add a `.devcontainer` file to your project directory and open the project in a container inside VSCode with the `Remote - Containers` extension. VSCode will mount your project directory at `/workspaces/<project-directory>` inside the container automatically. Any changes made inside that directory will be persisted in your project folder in your file system.

See an example of this set-up using a Go-Ethereum development environment here: https://github.com/MikeAleksa/solidity-hello-world-go

More info about VSCode devcontainers here: https://code.visualstudio.com/docs/remote/create-dev-container

**Comment by agoralive** [comment]
Thx

I will have a look at this, thank you!!!!!!!
